import { NextResponse } from "next/server";

type MiniAppProperties = Record<string, string | string[] | undefined>;

function withValidProperties(properties: MiniAppProperties) {
  return Object.fromEntries(
    Object.entries(properties).filter(([, value]) =>
      Array.isArray(value) ? value.length > 0 : Boolean(value)
    )
  );
}

export async function GET() {
  const appUrl = process.env.NEXT_PUBLIC_URL ?? "http://localhost:3000";

  return NextResponse.json({
    accountAssociation: {
      header: "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4NDQ3QjFDOTY5MThjNWY3MTZmZTFFQTY5QjJEOTY5QjUxMUI1MWJjQSJ9",
      payload: "eyJkb21haW4iOiJiYXNlLWNvaW4tc2NvcGUudmVyY2VsLmFwcCJ9",
      signature: "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAD9_BvEen_JwFB5GctXhk-gll21IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAPhSELIcxQMC9He6VmhtIBncm2etAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBxgsgBlIPFdOu4P3Zus0uLMYBWh6JXqcT3gDCD7Vi4OZn69u9Ot4Nbs8O_ZFoMTQaHyiJYM1F0ozCrivKRjW8bRsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI",
    },
    miniapp: withValidProperties({
      version: "1",
      name: "Base Price Tracker",
      homeUrl: appUrl,
      iconUrl: `${appUrl}/globe.svg`,
      splashImageUrl: `${appUrl}/next.svg`,
      splashBackgroundColor: "#000000",
      subtitle: "Track crypto prices on Base",
      description: "Live CoinMarketCap prices for BTC, ETH, SOL, and more.",
      screenshotUrls: [`${appUrl}/globe.svg`],
      primaryCategory: "finance",
      tags: ["prices", "crypto", "base"],
      heroImageUrl: `${appUrl}/globe.svg`,
      tagline: "Watch prices in real time",
      ogTitle: "Base Price Tracker",
      ogDescription: "Live CoinMarketCap prices with Base-friendly UI.",
      ogImageUrl: `${appUrl}/globe.svg`,
    }),
  });
}
